[tox]
envlist = py2.7, py3.4

[testenv:py2.7]
basepython=python2.7
deps= -rrequirements.txt
commands=
  pip install --upgrade pip
  pip install -r requirements.txt
  py.test []

[testenv:py3.4]
basepython=python3.4
deps=-rrequirements.txt
commands=
  pip3 install --upgrade pip
  pip3 install -r requirements.txt
  py.test []


# Run python3 tests with -bb flag. This will raise exceptions when bytestrings
# are compaired to strings. This caused one issue which seems to be fixed in
# the unreleased upstream pyasn1 module.
[testenv:py3.4-bb]
basepython=python3.4
deps=-rrequirements.txt
commands=
  pip3 install --upgrade pip
  pip3 install -r requirements.txt
  /bin/rm -rf {envdir}/lib/python3.4/site-packages/pyasn1
  /bin/rm -rf {envdir}/lib/python3.4/site-packages/pyasn1-0.1.9.dist-info
  pip3 install -r requirements-bb.txt
  python3 -bb -m pytest --network -v -s -x


[testenv:py2.7-full]
basepython=python2.7
deps=-rrequirements.txt
commands=
  /bin/rm -rf coverage2.7 && true
  pip install --upgrade pip
  pip install -r requirements.txt
  py.test --network --cov urlio --cov-report html
  /bin/mv htmlcov coverage2.7

[testenv:py3.4-full]
basepython=python3.4
deps=-rrequirements.txt
commands=
  /bin/rm -rf coverage3.4 && true
  pip install --upgrade pip
  pip install -r requirements.txt
  py.test --network --cov urlio --cov-report html
  /bin/mv htmlcov coverage3.4
